### ISSUE TITLE
Bug: Radio group control background should be Background/Primary

### ISSUE THREAD

**Issue by Phyele** [buildo/bento-design-system#298]
### Description of the bug

Radio group control background should be Background/Primary instead of transparent.

### Playroom reproduction

https://playroom.bento.buildo.io/#?code=N4Igxg9gJgpiBcIA8AhCAPABAIwIZgGsBzAJwgFcA7KAXgB0QBnCAMwBcUAbcmBgPmB1KmTAApRASkw0%2BmQcJGZIlRm0wBtAG65uMADSZGMNgDUdPALrTMAJRj42AOnJGAym1xsYoqrBYBLShgoCSFFTBJjchJhUTDwzCQbXCh-CABxMnIABwAxfxhOKHiEzAgSAsoPNjTKehBNGBIasB0GEoTOXGxC%2BoBNChJMFlxNQf8vJQhOcvh2hVLKXABbGHqRseiJmABaSBmSedKRbV0aYFOeAF8O8IhKAGEAC1xKIjXgI1NzGBuFhPuXGi50k0lkwCuf2OZWyNXujHO6luCXk0PClxg8EwDEyMBglAYemRpS6PU4WJxkXxhOJiiuRP%2BpVRaJOPwpICBvBADJZIlJhXZnJpjIS9NpImZLIx7LsxW54sU-PJ2JAsuFLLFIpEFihCQA9HwOqEFFcJJIhH8kHq0Og%2BNyQAB3fxQNhPRgIdQAJgArAA2AAMOqAA

### Version

0.11.4

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Edge

**Comment by gabro** [comment]
(as reported in #297)
