### ISSUE TITLE
Create Semantic Chip

### ISSUE THREAD

**Issue by Phyele** [buildo/bento-design-system#328]
Like Chip, but using the semantic tokens.
The Figma component is not yet ready.

**Comment by gabro** [comment]
You mean positive/negative/warning/info etc? Maybe we can call it FeedbackChip, or StatusChip? Or even, we could use the same Chip and extend the available colors?

What does this chip have that distinguishes it from the regular chip apart from the color?

**Comment by Phyele** [comment]
I would prefer "semantic" to connect them only to the colors, not giving interpretations of their use (status) or connecting them to other components (feedback).

I imagined them separated from the Chip for two reasons:
- a different use of color on labels (chip has all secondary label text, the semantic chip would have semantic color texts)
- a different configuration than a Chip (e.g. border-radius: 4px) that makes it clear that they are not categorical chips

![Image](https://user-images.githubusercontent.com/59652554/181740932-654ee965-0cf1-4bce-b7f8-fd531718d8fa.png)

**Comment by veej** [comment]
Closing as this will be part of the new Bento redesign
