### ISSUE TITLE
SelectionControlGroup: remove paddingY config

### ISSUE THREAD

**Issue by veej** [buildo/bento-design-system#347]
This config was used to add a vertical padding before the first item, but we agreed it should always be half of the spacing between the options. So we can remove the config entry and just use `config.internalSpacing \ 2` as vertical padding.

We agreed to apply the same logic also to horizontal groups (the padding top will be half the horizontal spacing between options)

**Comment by gabro** [comment]
This is technically breaking, right @veej ?

**Comment by veej** [comment]
yep, right
