### ISSUE TITLE
IllustrationProps "style" attribute raises a jsx-eslint warning

### ISSUE THREAD

**Issue by mperrando** [buildo/bento-design-system#371]
The name "style" of the attribute in https://github.com/buildo/bento-design-system/blob/edfc0ebe181c280afb65a270dc3c0ad82a897780/packages/bento-design-system/src/Illustrations/IllustrationProps.ts#L5 makes jsx-eslint to give the following warning

 https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/style-prop-object.md

**Comment by veej** [comment]
Hi @mperrando. You can selectively switch off the rule on specific elements with the `allow` config: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/style-prop-object.md#allow

Said so, it might make sense for us to avoid collisions by renaming the prop from `style` to something like `kind` (cc @gabro)
