### ISSUE TITLE
Multioptions SelectField can't accept string[] as value

### ISSUE THREAD

**Issue by LauGroupie95** [buildo/bento-design-system#376]
### Description of the bug

Hi @gabro and @veej ,
I tried to implement a multioptions selectField and if I set 
     value={["A", "B", "C"]}
is everything ok, otherwise if I set
     const selectedLetters : string[] = ["A", "B", "C"];
     value={selectedLetters}
there's an error saying that: 
  _Type 'string[]' is not assignable to type 'string[][]'.
  Type 'string' is not assignable to type 'string[]'.ts(2322)_

Please, can you help me?

Here's the code:

```ts
const optionsLetters = [
    {
        value: "A",
        label: "A",
        kind: "single-line",
    },
    {
        value: "B",
        label: "B",
        kind: "single-line",
    },
    {
        value: "C",
        label: "C",
        kind: "single-line",
    },
    {
        value: "D",
        label: "D",
        kind: "single-line",
    },
];

const selectedLetters = ["A", "B", "C"];

<SelectField
    name={""}
    value={selectedLetters}
    onChange={(v: string[]) => {
        console.log("selected", v);
    }}
    onBlur={() => {}}
    label="Letters"
    placeholder={""}
    options={optionsLetters}
    isMulti={true}
    multiValueMessage={(numberOfSelectedOptions: number) =>
        `${numberOfSelectedOptions} letters selected`
    }
    showMultiSelectBulkActions={true}
/>
```
        

### Version

0.12.2

**Comment by LauGroupie95** [comment]
Note that I tried also with version 0.13.3, but the problem is still present

**Comment by veej** [comment]
Looks like a weird TS issue. For some reason, if the value is passed as a variable, TypeScript infers the type of a single option as `string[]` (instead of just `string`) so the value for the multi-select results in `string[][]`. Not sure why this happens, or why the behaviour is different if we pass the value inline but, as a temporary solution, you can force the SelectField's type params explicitly:

```tsx
<SelectField<string, true>
   value={value}
   ...
/>
```

**Comment by LauGroupie95** [comment]
Thanks @veej,
it works perfectly!
