### ISSUE TITLE
Add support for colors in Display and Headline

### ISSUE THREAD

**Issue by marcopiii** [buildo/bento-design-system#421]
Currently, the components `Display` and `Headline` don't support the property `color` (they always use the primary color).

The other typography components support the following colors

|                  | Body         | Display      | Headline     | Label | Title        |
| ---------------- | ------------ | ------------ | ------------ | ----- | ------------ |
| Primary          | ✅ (as `default`) | ✅ (implicitly) | ✅ (implicitly) | ✅    | ✅ (as `default`) |
| Secondary        | ✅           |              |              | ✅    | ✅           |
| PrimaryInverse   | ✅           |              |              | ✅    | ✅           |
| SecondaryInverse |              |              |              | ✅    | ✅           |
| Interactive      |              |              |              |       |              |
| Informative      | ✅           |              |              | ✅    | ✅           |
| Positive         | ✅           |              |              | ✅    | ✅           |
| Warning          | ✅           |              |              | ✅    | ✅           |
| Negative         |              |              |              | ✅    | ✅           |
| Disabled         | ✅           |              |              | ✅    |              |

**Comment by marcopiii** [comment]
@Phyele we talked about letting the `Display` and `Headline` components take every text color, but the current situation seems a little bit more complex.
I reported the values currently accepted by all the components in the table above, can you please clarify what is the desired outcome?

**Comment by Phyele** [comment]
This is what I expect:

| | Body | Display | Headline | Label | Title |
| - | - | - | - | - | - |
| Primary | ✅ | ✅ | ✅ | ✅ | ✅ |
| Secondary | ✅ | ✅ | ✅ | ✅ | ✅ |
| PrimaryInverse | ✅ | ✅ | ✅ | ✅ | ✅ |
| SecondaryInverse | ✅ | ✅ | ✅ | ✅ | ✅ |
| Interactive | ✅ |  |  | ✅ |  |
| Informative | ✅ |  |  | ✅ | ✅ |
| Positive | ✅ |  |  | ✅ | ✅ |
| Warning | ✅ |  |  | ✅ | ✅ |
| Negative | ✅ |  |  | ✅ | ✅ |
| Disabled | ✅ |  |  | ✅ |  |
