### ISSUE TITLE
Improve line configuration in tabs and navigation

### ISSUE THREAD

**Issue by marcopiii** [buildo/bento-design-system#423]
In the Tabs component, the `lineHeight` accepts only the values of `borderBottomWidth`, while it should probably accept a `SizeConfig<number>` like the `activeVisualElement` of the Navigation component.

In the Tabs component, the `lineColor` accepts the values of "borderColor", while in the Navigation component the `lineColor` accepts the values of "background". We should probably unify them.

**Comment by marcopiii** [comment]
@Phyele regarding the `lineColor`, which one is the correct one?
- the Navigation's config uses a "background"
- the Tabs' config uses "borderColor"

**Comment by Phyele** [comment]
We should consider the line as a decoration, so both should be able to choose between all Brand colors and Foreground colors. This way, Outline colors should not be needed.
