### ISSUE TITLE
Add support for default padding in Card's configuration

### ISSUE THREAD

**Issue by marcopiii** [buildo/bento-design-system#425]
The Card component's configuration is
```
declare type CardConfig = {
    defaultRadius: Exclude<BentoSprinkles["borderRadius"], "circled">;
};
```

It makes sense to also support a `defaultPadding`.

Currently, it's implicitly `0`.

**Comment by marcopiii** [comment]
This one is tricky: should the `defaultPadding` refer to
- `padding`
- `{ paddingX, paddingY }`
- `{ paddingTop, paddingBottom, paddingLeft, paddingRight }`
- a union of the previous ones?

@gabro @veej

**Comment by veej** [comment]
@agnese could you please add your opinion here?

**Comment by gabro** [comment]
I think it would be ok to have something like:

```
type PaddingKey =
  | "paddingX"
  | "paddingY"
  | "paddingLeft"
  | "paddingRight"
  | "paddingTop"
  | "paddingBottom";

type DefaultPadding = number | { [k in PaddingKey]?: 0 | BentoSprinkles["padding"] }
```

which is basically what `Card` uses (with the shortcut `number` for `padding`)

**Comment by federico-ercoles** [comment]
Added in #682
