### ISSUE TITLE
Chip visualization in multiselect `SelectField`

### ISSUE THREAD

**Issue by marcopiii** [buildo/bento-design-system#435]
The `SelectField`, when in _multiselect_  mode, doesn't show all the selected values, just a recap like _"X elements selected"_. We should support also a different visualization, with the select values as chips in the field.

**Comment by veej** [comment]
cc @Phyele

**Comment by gabro** [comment]
Yes, we have a few options:
- truncate + ellipsis
- scroll horizontally
- grow vertically

A mixed approach (e.g. grow up to a number of lines then truncate, etc)

**Comment by gabro** [comment]
Discussed today with @Phyele @sarabi57 @federico-ercoles and @veej:
- let's add a "chip" option to `SelectField`, the field fill grow vertically if the options don't fit on a single line (we will discourage the use of this UI component if you foresee many options being selected in the UX guidelines, but at least we have the option available)
- in case the field is used for filtering, we can come up with a more complex pattern involving (potentially) a `SelectField` + external chips that represent the active filters. This is something we will explore as a UX guideline.
