### ISSUE TITLE
Create Pagination

### ISSUE THREAD

**Issue by Phyele** [buildo/bento-design-system#449]

**Comment by federico-ercoles** [comment]
What is MUI doing?

`Pagination` component:
* Icon buttons for previous/next page are shown by default, can be hidden with prop
* Icon buttons for first/last page are hidden by default, can be shown with prop
* Number of pages shown at boundaries configurable with prop, defaults to 1
* Number of pages shown before and after current page configurable with prop, defaults to 1
* Allows for both internal and external state control
* No control over page content

When displaying tabular data, they recommend using the `TablePagination` component, which allows for only scrolling one page at a time (via the previous/next page icon buttons), in return for being able to customise the number of rows displayed per page (default options are 10/25/50/100). Icon buttons for first/last page can be added via props.

**Comment by federico-ercoles** [comment]
Looking at the component in Figma, we could have a unique `Pagination` component, with these functionalities:
* Icon buttons for first/last and previous/next always shown
* Always 1 page shown at boundaries
* Always 1 page shown before and after current page
* "compact" mode which shows only pages and buttons, "extended" mode that shows configuration for number of rows per page

This component can then be both exposed to be used independently, and embedded in the `Table` component (with some configuration props re-exposed).

**Comment by federico-ercoles** [comment]
@gabro @Phyele thoughts on 

> Looking at the component in Figma, we could have a unique `Pagination` component, with these functionalities:
> 
> * Icon buttons for first/last and previous/next always shown
> * Always 1 page shown at boundaries
> * Always 1 page shown before and after current page
> * "compact" mode which shows only pages and buttons, "extended" mode that shows configuration for number of rows per page
> 
> This component can then be both exposed to be used independently, and embedded in the `Table` component (with some configuration props re-exposed).

@gabro @Phyele thoughts on this?

**Comment by gabro** [comment]
I think it makes sense.
I would start with the compact one, and take it from there.

Once we add the "extended" version we can also build it into Table
