### ISSUE TITLE
Support overflowing text in Typography components

### ISSUE THREAD

**Issue by federico-ercoles** [buildo/bento-design-system#495]

**Comment by federico-ercoles** [comment]
I have found two other DS that implement something similar:
* MUI: its `Typography` component accepts a `noWrap` boolean prop, that toggles showing the ellipsis on overflow.
* Ant: its various typography components accept a `ellipsis` prop, that is either a boolean (behaving like MUI's prop) or an object, if you want to set additional behaviours (like showing a tooltip when hovering the ellipsed text, showing a "more" button to expand the text, or configuring a multi-line ellipsis).

I think we could start simple and implement a basic ellipsis like MUI's, and expand it later with more functionalities like Ant's if we feel the need.

@gabro @Phyele thoughts?

**Comment by gabro** [comment]
> I think we could start simple and implement a basic ellipsis like MUI's, and expand it later with more functionalities like Ant's if we feel the need.

Yes, I agree with this. Let's start with a boolean prop, and leave the door open for more complex uses cases

**Comment by federico-ercoles** [comment]
Do we want this behaviour for all typography components?
