### ISSUE TITLE
Bad positioning of tooltips call-out

### ISSUE THREAD

**Issue by ghubguil** [buildo/bento-design-system#513]
### Description of the bug

The call-out "triangle" that is supposed to connect the tooltip icon and the tooltip textbox is sometimes misplaced in the middle of the tooltip area, over the text and partially covering it.
Here are some examples:
![01_tooltip_callout_issue](https://user-images.githubusercontent.com/67677446/213169073-8b3bbd23-8acc-4132-977f-d1911e3716b1.png)
![03_tooltip_callout_issue](https://user-images.githubusercontent.com/67677446/213191947-4a5ab9bc-b91f-49e5-a66c-4baaefdc7497.png)

---
Hopefully helpful clue... It seems that only tooltips opening to the left of the icon are affected. Those opening to the right look ok:
![01_tooltip_callout_ok](https://user-images.githubusercontent.com/67677446/213204647-0d281fa7-6ef4-4976-af96-791751b40ae8.png)

### Playroom reproduction

https://playroom.bento.buildo.io/#?code=N4Igxg9gJgpiBcIA8AVAlgGxgZwATYAcBDMGAXmACYAWAX10gwFcBbAO2woGZaA%2BAHTa5cg1BAgYALmgKDhkNpJiKy-ECnFSZuFjmxEA5jDVzckgE5oDR8xQAU5mADMANLgLmIBbAEpcZXlw7U2EkACEIAA9cRycKWPpgADoUjy9seig0QgwiAE9VEDQ2DGKYAFoAIwwIMABrNQEhYRakAEkFAHUiczZig3w0AC9yYABGADZ6AHomltwkaYjIudwfWkFZ0zEJaVlmhSUVNQ1d7V1sfSMTZosrG3tYtzTvPwCgkIXlmOd450SUkkXhlcFkcvlCsVSmwKtVag0QKt5u0uj0%2BmwBthhqNJjMkQsllFVutNqsdlp9vIIIplJJCqcKTo9IZjCBTHdrDBbMAHM5np5Xv5AsFmqFvrE-k4AakBSCwQRcgU1FCylUavVGp9Qh1qd1ev1BiMKLjcFtRQTlsSNmwzaEGXtTIdafTNHsmZcWTdhByHjynu5ZW9hZ9wlEfnFgAlcMkZelMtkFRDlSVVXCNYitQsdWw9ejMdjjVNTfjFpbTCSbWT7TJHdSjnSTq7zszrmzbpZOdzea4A%2Bkgx9zaHohLI-9o4DgfHwUqiimYWr4ZrzdrUfqMYacUXba1CSty9bt%2BSHQc687G2cCO6rqz2R3fd3%2BX2hQPkeLfqOpePY94p4mZyr5zTBF8RXXU0QNLEjXGLcS13K1SW2atKQYU9jnUJtLwua8vTMO8uUePle0Fd4RVfMMRyjGMgVlX9FUhOdYXVYDMxRMC13zKCTW3UI4P3BDmiPGsTxpNCkKvT0229PCu39YF%2B1I1o3wjSiJxo0EEzo5NoUYxcM2XLNVzzDdCzxENeOaCtDyQ2sRIbdCL3E1tb3ufC-UIuTnwUsVyPfFTvzlDSk1nbSF3TECDLYozIM3UzB3M4RLLJaZ0CwbAmhAWggA

### Version

0.15.3

**Comment by gabro** [comment]
Thanks for reporting! We've included a fix for this in the latest release (0.16.1)
