### ISSUE TITLE
Bug: Build time dts regression

### ISSUE THREAD

**Issue by gffuma** [buildo/bento-design-system#540]
### Description of the bug

Switching to Bento >= 0.15.5 make the build time of dts changes from ~2 s to ~24 s (on my MacBookPro M2 2022).

I follow the instructions of design system repository from the documentation.
I create a repository to reproduce the bug:

Fast:
https://github.com/gffuma/repro-bento-build-time-regression

Slow:
https://github.com/gffuma/repro-bento-build-time-regression/tree/slow

### Version

>= 0.15.5

**Comment by gabro** [comment]
Closed by #542
