### ISSUE TITLE
Bug: Missing needed native HTML properties 

### ISSUE THREAD

**Issue by bvkimball** [buildo/bento-design-system#549]
### Description of the bug

A button can have a `name` and a `value` for when it is used within a Form.  You can set these native HTMLButtonElements because of the typings.

I think you should include something like the following

```diff
type Props = {
  label: LocalizedString;
 // ...
} 
& Omit<AriaButtonProps<"button">, "onPress"> 
+ & React.HTMLProps<HTMLButtonElement>;
```

or Just the props you want to expose include
```diff
+ & Pick<React.HTMLProps<HTMLButtonElement>, "name" | "id">;
```

or  cleaner 
```diff
+ type IncludedHTMLButtonProps = Pick<React.HTMLProps<HTMLButtonElement>, "name" | "id">;
// ...
+ & IncludedHTMLButtonProps;
```

I think you should do the same for TextFields too, I personally need access to `onKeyDown` event

```diff
+ & React.HTMLProps<HTMLInputElement>;
```

### Playroom reproduction

https://playroom.bento.buildo.io/#?code=N4Igxg9gJgpiBcIA8AhArgFwxAdgAgBsBDAIxgIF4AdEAFRgGcMa8ciBbGakIsDAS1wsA9AD4qOEAF8gA

### Version

1.17.1

### What browsers are you seeing the problem on?

Chrome

**Comment by bvkimball** [comment]
@gabro I can submit a PR for this.  It might more sense to just add and expose these behaviors in the same DX your already are for additional events..

**Comment by gabro** [comment]
Thank you for reporting @bvkimball! I agree we should support more stuff. If you have time to send a PR I'll gladly review it. As a general rule we tend to start small in terms of API surface and grow it if needed, so I like the cherry-picking approach you proposed.
