### ISSUE TITLE
Refactor of box shadow sprinkles

### ISSUE THREAD

**Issue by Phyele** [buildo/bento-design-system#591]
## Description
`boxShadow` sprinkles should be inferred from the outline colors, without the need to set theme variables twice, one for the `outline` prop (with only the color), one for the `box-shadow` prop (with shadow params + color).

We should define a set of possible shadow "configurations" (like `inset`, `insetStrong`, `insetBottom`, ...) and mix them with the outline colors to have resulting sprinkles values for boxShadow like `outlineDecorativeInset`, `outlineDecorativeInsetStrong`, ....

**Comment by veej** [comment]
Closing as this will be part of the new theme / sprinkles redesign
