### ISSUE TITLE
Bug: Button Labels don't scale with size

### ISSUE THREAD

**Issue by Gtoffo** [buildo/bento-design-system#616]
### Description of the bug

Button text labels have a single fixed size while buttons can scale L-M-S.

Compare to MUI https://mui.com/material-ui/react-button/#sizes where the label text scales appropriately.

It is impossible to select an appropriate text size for all three sizes

### Version

2.7

### Figma version

Latest

**Comment by gabro** [comment]
Hi @Gtoffo, thanks for reporting! This used to be a design choice, but we're now in the process of revisiting it in Bento 3.0, where it will vary by default.

That said, we can easily add this in a non-breaking way, so I'm doing it in #617.

The default config will maintain the current behavior, but you'll be able to configure it differently.

**Comment by Gtoffo** [comment]
Thanks guys!
