### ISSUE TITLE
Bug: Cannot read properties of null when backspace on hour field

### ISSUE THREAD

**Issue by gffuma** [buildo/bento-design-system#767]
### Description of the bug

https://github.com/buildo/bento-design-system/blob/40280a12a040eded481e78fa7154d2178bf6bdd5/packages/bento-design-system/src/TimeField/TimeField.tsx#L30C1-L30C1

I think that `value` can also be null.
```ts
 const onChange = (value: TimeValue) => {
    const time = new Time(value.hour, value.minute, value.second, value.millisecond);
    return props.onChange(time);
  };
```

### Playroom reproduction

Easy to reproduce go here:

https://developer.bento-ds.com/Components/TimeField/

Press backspace into the hour field got runtime error.

### Version

v0.20.2

**Comment by gabro** [comment]
Thanks for reporting! A fix is coming in #768
