### ISSUE TITLE
Bug: Column is not working with RSC

### ISSUE THREAD

**Issue by veej** [buildo/bento-design-system#835]
### Description of the bug

Trying to bootstrap a new Next.js application with App Router, and using `Columns` in a server component (e.g. a layout), it seems the `width` set on explicit `Column` components is ignored. E.g.

```
<Columns space={0}>
   <Column width="1/3">
       ....
   </Column>
   <Column width="2/3">
      ...
   </Column>
</Columns>
```
The code above will result in two `Column`s splitting the available space in half, instead of respecting the 1/3 - 2/3 proportion.

Inspecting the generated HTML code, it seems the `Column` component with the right flex-basis is wrapped in another `Column`, as if bento is not able to recognize the child is a `Column`:
<img width="1466" alt="image" src="https://github.com/buildo/bento-design-system/assets/925635/4354bb9a-b11f-46b2-addd-4b06a8debb9b">

It seems, for reasons, the `isColumn` function to detect if a child of `Columns` is a `Column` doesn't work as expected with RSC.

### Version

0.22.9

### What browsers are you seeing the problem on?

Chrome

**Comment by pedrodim** [comment]
React replaces every server component with a _lazy_  node so the check on `child.type === Column` doesn't work.

7 = Column; 8 = Column
<img width="227" alt="Screenshot 2024-08-15 at 19 24 08" src="https://github.com/user-attachments/assets/590c5d5c-1c53-4d35-8b4e-24fc5d0abeff">

Probably the check should check for _lazy_ nodes generated by RSC as well as _normal_ nodes as [suggested here](https://stackoverflow.com/questions/77057711/how-to-get-component-type-of-a-reacy-lazy-component). Keep in mind the solution on stackoverflow already doesn't work as the `_payload`'s value has already changed (before object, now array), meaning any React update could break the check again.

Lazy node's `type`, note `_payload.value`.
<img width="621" alt="Screenshot 2024-08-15 at 19 25 39" src="https://github.com/user-attachments/assets/52d79371-d77b-4a4e-8823-8892f40c9846">

Importing the `Column` component with an alias, like `import { Column as C } from '...'`, doesn't reflect on the payload so we can assume it is safe to check the string "Column".

As a side note, the check doesn't work on lazy elements (using `React.lazy`) but that's expected, and this fix wouldn't fix it as the payload doesn't contain any reference to that it's loading.
