### ISSUE TITLE
Bug: @buildo/bento-design-system only contains a package.json

### ISSUE THREAD

**Issue by JamieMason** [buildo/bento-design-system#883]
### Description of the bug

Hi,
I'm trying Bento for the first time by following https://developer.bento-ds.com/Getting%20Started/quick-start/.

The package only contains a package.json file and nothing more – is that correct?

This applies to these versions:
https://www.npmjs.com/package/@buildo/bento-design-system/v/0.22.22?activeTab=code
https://www.npmjs.com/package/@buildo/bento-design-system/v/0.22.21?activeTab=code

This one is OK though and contains code:
https://www.npmjs.com/package/@buildo/bento-design-system/v/0.22.17?activeTab=code

Thanks,

Jamie

### Version

0.22.22

**Comment by gabro** [comment]
Woops, thank you for reporting! 
We recently changed the CI system for release and it seems there's a bug in it. I'll try to get to it asap

**Comment by gabro** [comment]
Ok, this seems to be fixed now. I've manually verified that version 0.22.23 shows all the files at https://www.npmjs.com/package/@buildo/bento-design-system?activeTab=code.

Thanks again for the bug report @JamieMason!
